#!/bin/bash

if [[ $# -eq 0 ]] ; then
    exec /usr/bin/supervisord -c /etc/supervisord.conf --nodaemon
else
    export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    exec "$@"
fi
